#!/bin/bash

#sudo apt -y install python-ssdeep libfuzzy-dev libv8-dev libboost-all-dev

#pip install thug

#mkdir -p ~/irrvitools/builds/pyv8
#cd ~/irrvitools/builds/pyv8
#git clone https://github.com/buffer/pyv8
#cd pyv8
#git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
#export PATH=$PATH:~/irrvitools/builds/pyv8/pyv8/depot_tools
#chmod -R +x depot_tools
#fetch v8; cd v8; gclient sync; ./build/install-build-deps.sh; tools/dev/gm.py x64.release
#export V8_HOME=


#cd ~/irrvitools/builds/pyv8/pyv8
#python setup.py build
#sudo python setup.py install
apt -y install libv8-dev libboost-all-dev libfuzzy-dev libgraphviz-dev python-ssdeep; pip install thug
